### ISSUE TITLE
Multiple instances of SE using addin

### ISSUE THREAD

**Issue by OkkermanD** [SolidEdgeCommunity/SolidEdge.Community.AddIn#1]
Dear Jason,

I'm playing around with the AddIn Demo you've created and it looks very good! The only thing I am wondering is the fact that, when I register the dll and start Solid Edge a second instance opens on the background (see image). Is this normal behaviour or am I doing something wrong? By the way, I'm using ST6 64bit on Windows 7.

Thanks in advance for your time.

![capture_2016_01_26_10_01_15_588](https://cloud.githubusercontent.com/assets/16895312/12576886/309fb4ae-c417-11e5-8a10-831188104b0a.png)

**Comment by jlnewell** [comment]
Under no circumstance should 2 instances of Edge.exe be started. Terminate the processes manually to make sure none are running. Watch my video https://youtu.be/ilN4ntB9w_I?t=66 and make sure you're following the same steps. When you debug the addin in Visual Studio, it should launch a single instance of Solid Edge. If that's not the case, report back and I'll dig a little deeper.

**Comment by OkkermanD** [comment]
Thanks for your answer,

It turns out I made a stupid mistake in the OnConnectToEnvironment sub section. When hooking to the SE events the code accidentally created a new SE instance instead of using the current environment.
Apologizes for bothering you.
