### ISSUE TITLE
Help event is not fired!

### ISSUE THREAD

**Issue by loginator** [SolidEdgeCommunity/SolidEdge.Community.AddIn#2]
The Help event is not fired when pressing the F1 key.
I used the AddIn template and just changed the MyRibbon class:

```
class MyRibbon : SolidEdgeCommunity.AddIn.Ribbon
{
    private RibbonButton _button1;

    public MyRibbon()
    {
        // Get a reference to the current assembly. This is where the ribbon XML is embedded.
        var assembly = System.Reflection.Assembly.GetExecutingAssembly();

        // Note: In this example, the ribbon XML file has a build action of "Embedded Resource".
        var _embeddedResourceName = String.Format("{0}.xml", this.GetType().FullName);
        this.LoadXml(assembly, _embeddedResourceName);

        // Example of how to bind a local variable to a particular ribbon control.
        _button1 = GetButton(0);
        _button1.Help += _button1_Help;
    }

    void _button1_Help(RibbonControl control, IntPtr hWndFrame, int helpCommandID)
    {
        Help.ShowHelp(null, "Help.chm");
    }
}

```

Nothing gets called when pressing the F1 key while the cursor is on the RibbonButton.

**Comment by loginator** [comment]
After making some tests with the source code and the test add in i noticed that the function `void SolidEdgeFramework.ISEAddInEventsEx.OnCommandHelp(int hFrameWnd, int HelpCommandID, int CommandID)` never gets called. Instead of this function the function 'void SolidEdgeFramework.ISEAddInEventsEx.OnCommandOnLineHelp(int HelpCommandID, int CommandID, out string HelpURL)' gets called. Is that the normal behaviour or is this a bug?

**Comment by jlnewell** [comment]
I vaguely recall looking at this in the past. I see your pull request and will review\test it. Thank you for your contribution. If everything looks good, I'll get a new NuGet package out tonight.
